### ISSUE TITLE
Exception 0xc000001d

### ISSUE THREAD

**Issue by rubenv** [lukechampine/fastxor#2]
For some reason, fastxor seems to crash:

```
Exception 0xc000001d 0x0 0x0 0x13d301c
PC=0x13d301c

github.com/lukechampine/fastxor.xorBytesAVX(0xc0004a9600, 0x1aee, 0x1aee, 0xc0004a6000, 0x1aee, 0x1aee, 0xc0004a7b00, 0x1aee, 0x1aee, 0x1aee, ...)
	github.com/lukechampine/fastxor@v0.0.0-20200124170337-07dbf569dfe7/xor_amd64.s:94 +0x5c
github.com/lukechampine/fastxor.Bytes(0xc0004a9600, 0x1aee, 0x1aee, 0xc0004a6000, 0x1aee, 0x1aee, 0xc0004a7b00, 0x1aee, 0x1aee, 0x0)
	github.com/lukechampine/fastxor@v0.0.0-20200124170337-07dbf569dfe7/xor_amd64.go:36 +0x1ae
```

This is on `Windows 10 Pro - 10.0.19042`, with `Intel(R) Core(TM) i7-3770 CPU @ 3.40 GHz` CPU.

Specs for this CPU are here: https://ark.intel.com/content/www/us/en/ark/products/65719/intel-core-i7-3770-processor-8m-cache-up-to-3-90-ghz.html

I'm completely out of my depth here (sadly not an expert on assembly), but if I read it correctly, the problematic code is 256 bit AVX. This page (https://www.felixcloutier.com/x86/pxor) leads me to believe that this code requires AVX2, which (if I read it correctly), this CPU doesn't support.

Is it possible the check needs to be extended?

**Comment by rubenv** [comment]
I'm guessing the fix should be to change this:

```
	case cpu.X86.HasAVX:
		xorBytesAVX(dst, a, b, n)
```

To this:

```
	case cpu.X86.HasAVX2:
		xorBytesAVX(dst, a, b, n)
```

Would that be correct?

I'll make a PR if that's the case.

**Comment by lukechampine** [comment]
Yes, I think you're right. This was some of the first asm I wrote, so I'm not surprised I got something subtly wrong... it looks like on AVX, `VPXOR` is only supported on 128-bit registers (X0, X1, etc.), whereas I'm using it on 256-bit registers (Y0, Y1, ...).

In theory I could add an AVX routine that uses 128-bit registers, but it's pretty uncommon for CPUs to not support AVX2 these days, so I think the check should just be changed to `AVX2` (and perhaps the routines should be renamed to `AVX2` as well). A PR for that would be great.

**Comment by rubenv** [comment]
PR submitted.

This fix is good enough for me. The machines where we need the ultra-high performance all have AXV2 anyway. The binary that's distributed to clients only uses fastxor in a not-so-hot code path, a fallback to SSE for those is fine.
