### ISSUE TITLE
not faster on Core i5 with 64-byte blocks and golang 1.16

### ISSUE THREAD

**Issue by nerdralph** [lukechampine/fastxor#4]
I tested fastxor for use with some keccak code I've been writing, and it's no faster on aligned 64-byte blocks than the plain go code I've been using:
```
const wordSize = int(unsafe.Sizeof(int(0)))

// XORs multiples of 4 or 8 bytes (depending on architecture.)
// The arguments must be of equal length.
func fastXORWords(dst, a, b []byte) {
    dw := *(*[]uintptr)(unsafe.Pointer(&dst))
    aw := *(*[]uintptr)(unsafe.Pointer(&a))
    bw := *(*[]uintptr)(unsafe.Pointer(&b))
    n := len(b) / wordSize
    for i := 0; i < n; i++ {
        dw[i] = aw[i] ^ bw[i]
    }
}
```

The profiling results show that my code gets inlined, which probably makes up for the slower 64-bit operations vs the 128-bit SSE instructions used by fastxor.
FWIW, when I tried partially unrolling the loop, I did not see a material change in performance.  With 2 xor ops per loop iteration, it was still inlined, and with 4 ops per loop it was no longer inlined.

p.s. here's the profile results from one of the fastxor test runs:
```
Showing top 10 nodes out of 13
      flat  flat%   sum%        cum   cum%
    2530ms 77.13% 77.13%     2530ms 77.13%  github.com/nerdralph/crypto/sha3.keccakF1600
     290ms  8.84% 85.98%      290ms  8.84%  github.com/lukechampine/fastxor.xorBytesSSE
     250ms  7.62% 93.60%     3180ms 96.95%  main.makeCacheFast
     100ms  3.05% 96.65%      100ms  3.05%  runtime.cgocall
```

**Comment by lukechampine** [comment]
Yeah, for small blocks the asm overhead is much more noticeable.  On my machine (with AVX2) it's worth it at 64 bytes, but I'm not surprised that it's different on other hardware.

For something like Keccak I'd recommend writing as much as possible in asm anyway. [Avo](https://github.com/mmcloughlin/avo) makes it much easier!
